### PR TITLE
Filter by both raw_filter and filters simultaneously

### PR DESCRIPTION
**Pull request by teeberg**
It only makes sense to be able to combine a raw filter and a dict of filters, so that you can first filter by the one and then by the other. We only need to pay attention to not filter by an empty dict because no filters would match and all activities would be removed from the result set.

### CODE REVIEW

**Comment by numan** [comment]
@teeberg can you look at the failing test?

**Comment by teeberg** [comment]
@numan There you go! Should I document the changed behavior somewhere?

**Comment by numan** [comment]
Maybe add a changelog to the readme?

**Comment by teeberg** [comment]
@numan There you go again! :)

**Comment by teeberg** [comment]
One sec, let me tweak that changelog. It doesn't come out right on GitHub.

**Comment by teeberg** [comment]
One sec, I'll tweak the changelog to look better on GitHub.

**Comment by teeberg** [comment]
@numan What do you think?

**Comment by numan** [comment]
looks good!

**Pull request merged**
